### ISSUE TITLE
Fix all threads view

### ISSUE THREAD

**Issue by hamlim** [hamlim/slack-night-mode#1]
Related issue:  https://github.com/laCour/slack-night-mode/issues/218

css snippet:

```css
.p-threads_view {
  background: #222;
}

.p-threads_view__divider_line {
  border-color: #111;
}

.p-threads_view__divider_label {
  background: #111;
}

.p-threads_view_header__channel_name {
  color: #c7c7c7;
}

.p-threads_view_root {
  border-color: #444;
}

.p-threads_view_reply {
  border-color: #444;
}

.p_threads_view_load_newer_button,
.p_threads_view_load_older_button {
  background: rgba(255, 255, 255, 0.05);
  border-color: #444;
}

.p-threads_view__footer {
  border-color: #444;
}

.p-threads_view__default_background {
  background: rgba(255, 255, 255, 0.05);
}
```
